name: 'Setup Node.js'
description: 'Setup a specific Node.js version using actions/setup-node with caching'
inputs:
  node-version:
    description: 'Version of Node.js to use'
    required: false
    default: '20.x'
  always-auth:
    description: 'Always authenticate'
    required: false
    default: 'true'
  cache:
    description: 'Package manager to cache'
    required: false
    default: 'npm'
  cache-dependency-path:
    description: 'Path to dependency lock file'
    required: false
    default: 'package-lock.json'

outputs:
  node-version:
    description: 'Version of Node.js that was setup'
    value: ${{ steps.node-version.outputs.node-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      id: node-version
      with:
        node-version: ${{ inputs.node-version }}
        always-auth: ${{ inputs.always-auth }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Verify setup
      shell: bash
      run: |
        echo "✅ Node.js $(node --version) is ready"
        echo "✅ NPM $(npm --version) is ready"
        echo "✅ Cache directory: $(npm config get cache)"