name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make this project better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What's the problem you're trying to solve?
      placeholder: The current system doesn't handle X well because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I think we should add a new feature that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I also considered X, but it wouldn't work because...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: |
        Screenshots, mockups, or examples of similar features in other tools.

        Related issues or discussions: #123

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that describe this idea
          required: true
        - label: This feature would benefit other users, not just me
          required: true
        - label: I understand this is a suggestion and implementation depends on project priorities
          required: true